apiVersion: services.miloapis.com/v1alpha1
kind: Service
metadata:
  name: interconnect
spec:
  description: |
    Private, dedicated network connectivity between Datum Cloud and external networks.
  displayName: Interconnect
  owner:
    producerProjectRef:
      name: datum-cloud
  enablementPolicy:
    mode: GatedByProvider
  phase: Published
  serviceName: interconnect.datumapis.com
